
Genre.create([
               { name: 'Fiction' },
               { name: 'Non-Fiction' },
               { name: 'Science Fiction' },
               { name: 'Fantasy' },
               { name: 'Mystery' },
               { name: 'Biography' },
               { name: 'Romance' },
               { name: 'Thriller' },
               { name: 'Historical' },
               { name: 'Self-Help' },
               { name: 'Adventure' },
               { name: 'Horror' },
               { name: 'Young Adult (YA)' },
               { name: 'Children\'s Literature' },
               { name: 'Dystopian' },
               { name: 'Magical Realism' },
               { name: 'Graphic Novel' },
               { name: 'Poetry' },
               { name: 'Crime' },
               { name: 'Anthology/Short Stories' },
               { name: 'Classic' },
               { name: 'LitRPG' },
               { name: 'Chick Lit' },
               { name: 'Western' },
               { name: 'Political Thriller' },
               { name: 'Cyberpunk' },
               { name: 'Historical Fiction' },
               { name: 'Urban Fantasy' },
               { name: 'Family Saga' },
               { name: 'Metafiction' }
             ]);